name: build deb

on:
  push:
    branches:
      - main
      - master
    paths:
      - '*.h'
      - '*.m'
      - '*.mm'
      - '*.x'
      - '*.xm'
      - '*.c'
      - '*.cc'
      - '*.cpp'
      - '*.s'
      - '*.S'
      - 'YukiPreventDelete.plist'
      - 'control'
      - 'Makefile'
      - 'layout/**'
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Prepare Theos
        uses: huami1314/theos-action@main

      - name: Setup GNU Make
        run: |
          echo "$(brew --prefix)/opt/make/libexec/gnubin" >> $GITHUB_PATH

      - name: Clean packages dir
        run: rm -rf packages && mkdir -p packages

      - name: Build Rootless
        run: |
          make package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1 -j$(sysctl -n hw.ncpu)
          for f in packages/*.deb; do
            [ -f "$f" ] && [[ "$f" != *"-root"*".deb" ]] && mv "$f" "${f%.deb}-rootless.deb"
          done

      - name: Upload package artifacts
        uses: actions/upload-artifact@v7
        with:
          name: YukiPreventDelete
          path: |
            ${{ github.workspace }}/packages/*.deb
